[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#101cca"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8faff"
textColor = "#262730"
font="Inter, sans-serif"


[[theme.fontFaces]]
family="Inter"
url="https://fonts.gstatic.com/s/inter/v3/UcCO3FwrKj5t6tQ6aUQ.woff2"
style="italic"
weight="200 1000"

[[theme.fontFaces]]
family="Inter"
url="https://fonts.gstatic.com/s/inter/v3/UcCO3FwrKj5t6tQ6aUQ.woff2"
style="normal"
weight="200 1000"
